### ISSUE TITLE
Test script doesn't work on OSX

### ISSUE THREAD

**Issue by ianobermiller** [UXtemple/babel-plugin-react-autoprefix#7]
I'm probably doing something wrong, but running `npm test` fails with:

```
➜ bash .bin/test                                                                                                                                            22:43:47
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

It would be best to eliminate shell scripts so that tests can be run on any platform.

**Comment by dariocravero** [comment]
Mmm, might it be because I'm on GNU's find? Here's my `find --version`:

```
find (GNU findutils) 4.4.2
Copyright (C) 2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Built using GNU gnulib version e5573b1bad88bfabcda181b9e0125fb0c52b7d3b
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS() CBO(level=0)
```

What does yours look like?

**Comment by ianobermiller** [comment]
Looks like the problem isn't `find`, its using `||` to set defaults. It works fine if it is done the bash way, `where=${1:-.}`. I'll send a PR.

**Comment by dariocravero** [comment]
Thanks :). Also, for moving away from using bash scripts, I'm happy to do so, but there's one catch with testing the plugins: it has to be available as a package installed in `node_modules` for [babel to resolve it correctly](https://github.com/UXtemple/babel-plugin-react-autoprefix/blob/master/__tests__/get-code.es6#L5). That's why we need [the symlink](https://github.com/UXtemple/babel-plugin-react-autoprefix/blob/master/.bin/test#L9).

**Comment by ianobermiller** [comment]
symlink shouldn't be a problem: https://nodejs.org/api/fs.html#fs_fs_symlink_srcpath_dstpath_type_callback
